spring:
  application:
    name: server
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticdb?useSSL=false
    username: root
    password: 1997
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        shema_update: true
  logging:
    level: 
      ROOT: INFO