spring:
  application:
    name: server
  datasource:
    driverClassName: com.mysql.cj.jdbc.driver
    dialect: org.hibernate.dialect.MySQL57Dialect
    url: jdbc:mysql://localhost:3306/pruebasb?useSSL=false
    user: root
    password: 1997
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        shema_update: true